package com.argus.enums;

public enum RiskSignal {

    AUTHORIZED_AGENT,
    AUTHORIZED_RESOURCE,
    VALID_STATE_TRANSITION,
    WITHIN_BUDGET,

    UNKNOWN_TASK,
    UNAUTHORIZED_AGENT,
    UNAUTHORIZED_RESOURCE,
    INVALID_STATE_TRANSITION,
    AMOUNT_MANIPULATION,
    INSUFFICIENT_BUDGET,
    EXPIRED_AUTHORITY,
    DUPLICATE_EXECUTION
}