spring.application.name=argus

# DataSource Configuration
spring.datasource.url=jdbc:mysql://localhost:3307/argus
spring.datasource.username="your_username"
spring.datasource.password="your_password"
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Prevent unnecessary warning
spring.jpa.open-in-view=false
